### ISSUE TITLE
Kosovo is missing some attributes

### ISSUE THREAD

**Issue by ENT8R** [ideditor/country-coder#17]
![kosovo](https://user-images.githubusercontent.com/25306497/73747414-ae497d00-4757-11ea-9a5c-74a32884462d.png)
The Kosovo is missing both an `iso1A3` and `iso1N3` attribute which makes it impossible to find e.g. the `iso1A2` attribute using the following code:
```javascript
import { iso1A2Code } from '@ideditor/country-coder';  
iso1A2Code('XKX');
```

**Comment by quincylvania** [comment]
Thanks, @ENT8R. Country-coder is missing these since Kosovo doesn't have officially-assigned ISO codes. `XK` is in the user-assignable namespace. Additionally, I learned the US FIPS code for Kosovo is `KV`, so we'll add that as an alias.

It does look like `XKX` is used as the alpha-3 equivalent, so I'll add that. I couldn't find a numeric code but let us know if you see one.

**Comment by ENT8R** [comment]
Thank you for your explanation!
I did a quick research too and found the following paragraph on this page: https://www.iso.org/iso-3166-country-codes.html
> Following notification from the United Nations (UN), the ISO 3166 maintenance agency assigns alpha-2 and alpha-3 country code elements to new UN member states. The numeric country code is assigned by the UN.

Obviously, the Kosovo is not yet an UN member state ([98 of 193 UN member states recognize the Kosovo as a state](https://en.wikipedia.org/wiki/International_recognition_of_Kosovo)), so it should not have a numeric country code yet too...
