### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by peternewman** [ideditor/country-coder#29]
Hi,

Any chance of a new release so we can have access to all the new sub-places:
https://github.com/ideditor/country-coder/compare/v3.2.0...master

**Comment by quincylvania** [comment]
@peternewman Yes, we definitely need a release soon. There are a few outstanding items to work out…

The big one is that we need a way to say "this feature 1 isn't part of feature 2, but feature 2 has sovereignty over feature 1". For example, the Channel Islands and the British Overseas Territories aren't technically in the UK, so country-coder shouldn't say they are unless you want it to.

Since NSI needs the new detail for Hacktoberfest I'll try to do this soon.

**Comment by peternewman** [comment]
> @peternewman Yes, we definitely need a release soon. There are a few outstanding items to work out…
> 
> The big one is that we need a way to say "this feature 1 isn't part of feature 2, but feature 2 has sovereignty over feature 1". For example, the Channel Islands and the British Overseas Territories aren't technically in the UK, so country-coder shouldn't say they are unless you want it to.

According to this, the Channel Islands are probably in it, depending on what feature 2 is:
https://en.wikipedia.org/wiki/Terminology_of_the_British_Isles#/media/File:British_Isles_Euler_diagram_15.svg

> Since NSI needs the new detail for Hacktoberfest I'll try to do this soon.

Great thanks.

**Comment by quincylvania** [comment]
Done: https://github.com/ideditor/country-coder/releases/tag/v4.0.0

I didn't end up doing anything fancy to solve the UK problem, but I don't think it'll be much of an issue.

**Comment by peternewman** [comment]
Thanks @quincylvania , funny enough I was just wondering if there had been any progress.

I assume you just mean this hasn't been implemented yet?
> The big one is that we need a way to say "this feature 1 isn't part of feature 2, but feature 2 has sovereignty over feature 1".

**Comment by quincylvania** [comment]
> I assume you just mean this hasn't been implemented yet?

@peternewman Correct. This shouldn't really matter for most use cases, but it's something to keep in mind.
